Allow File::Temp handles to be guessed correctly
libwww-perl/LWP-MediaTypes pull request #1
Opened 2019-03-08 19:34 UTC by waterkip

The previous implementation only allowed URI objects to be guessed
correctly. This changeset implements `$file->can('')` so we can deal
with other kind of objects as well. If an object cannot `path()` or
`filename()` we stringify the object as a last resort.

2019-03-08 19:45 UTC, karenetheridge reviewed
I'm not a fan of wholesale tidying, as it makes subsequent 'blame's more difficult. The previous style is readable enough to not be offensive to the eyes.

2019-03-08 20:46 UTC, oalders approved these changes

2019-03-13 15:42 UTC, oalders requested changes

2019-03-13 15:42 UTC, oalders commented on lib/LWP/MediaTypes.pm
> +        if ($file->can('path')) {
@genio pointed out that we should probably check that this is `blessed` before we check `can`.

2019-03-13 17:53 UTC, oalders approved these changes

2019-03-13 17:54 UTC, merged

2019-03-13 17:54 UTC, oalders commented
Thanks @waterkip!

2019-03-19 17:05 UTC, Grinnz commented
FYI, though it doesn't matter a whole lot, the stringification alone would work for both URI and File::Temp objects (as well as any other relevant ones I can think of).